const Data = [
  {
    id: '1',
    name: 'Poha',
    lastname: 'Luna',
    category: 'Backend',
    language: ['JS', ' ', 'PHP', ' ', 'PYTHON', ' ', 'JAVA'],
    costo: '100 MX$',
    redes: ['JS', 'PHP'],
    img: 'images/john-schnobrich-FlPc9_VocJ4-unsplash.jpg',
    desc: 'ppp Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. ',
    nameColor: {color: 'blue', background: '#e7f1ff00'},
  },
  {
    id: '2',
    name: 'noha',
    lastname: 'Luna',
    category: 'Frontend',
    language: ['JS', ' ', 'PHP', ' ', 'PYTHON', ' ', 'JAVA'],
    costo: 'Free',
    redes: ['JS', ' ', 'PHP'],
    img: 'images/john-schnobrich-FlPc9_VocJ4-unsplash.jpg',
    desc: 'ppp Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. ',
    nameColor: {color: 'blue', background: '#e7f1ff00'},
  },
  {
    id: '3',
    name: 'Polha',
    lastname: 'Luna',
    category: 'Full Stack',
    language: ['JS', ' ', 'PHP', ' ', 'PYTHON', ' ', 'JAVA'],
    costo: '100 MX$',
    redes: ['JS', ' ', 'PHP'],
    img: 'images/john-schnobrich-FlPc9_VocJ4-unsplash.jpg',
    desc: 'ppp Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. ',
    nameColor: {color: 'blue', background: '#e7f1ff00'},
  },
  {
    id: '4',
    name: 'pPoha',
    lastname: 'Luna',
    category: 'Backend',
    language: ['JS', ' ', 'PHP', ' ', 'PYTHON', ' ', 'JAVA'],
    costo: '120 MX$',
    redes: ['JS', ' ', 'PHP'],
    img: 'images/john-schnobrich-FlPc9_VocJ4-unsplash.jpg',
    desc: 'ppp Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. ',
    nameColor: {color: 'blue', background: '#e7f1ff00'},
  },
  {
    id: '5',
    name: 'fPoha',
    lastname: 'Luna',
    category: 'Backend',
    language: ['JS', ' ', 'PHP', ' ', 'PYTHON', ' ', 'JAVA'],
    costo: 'Free',
    redes: ['JS', ' ', 'PHP'],
    img: 'images/john-schnobrich-FlPc9_VocJ4-unsplash.jpg',
    desc: 'ppp Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. ',
    nameColor: {color: 'blue', background: '#e7f1ff00'},
  },
  {
    id: '6',
    name: 'pkPoha',
    lastname: 'Luna',
    category: 'Full Stack',
    language: ['JS', ' ', 'PHP', ' ', 'PYTHON', ' ', 'JAVA'],
    costo: '80 MX$',
    redes: ['JS', ' ', 'PHP'],
    img: 'images/john-schnobrich-FlPc9_VocJ4-unsplash.jpg',
    desc: 'ppp Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. ',
    nameColor: {color: 'blue', background: '#e7f1ff00'},
  },
];

export default Data;
